# Generated by Django 4.1.7 on 2023-04-07 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=45)),
                ('date_of_birth', models.DateTimeField(blank=True)),
                ('profile_status', models.CharField(choices=[('0_new', 'new'), ('1_activated', 'activated'), ('2_banned', 'banned'), ('3_deleted', 'deleted')], default='0_new', max_length=32)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('family_status', models.CharField(blank=True, max_length=45)),
                ('about', models.CharField(blank=True, max_length=128)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.CharField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
