# Generated by Django 4.1.7 on 2023-04-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_car_zavod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
