# Generated by Django 4.1.7 on 2023-04-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_theme',
            field=models.BooleanField(default=False),
        ),
    ]
