# Generated by Django 4.1.7 on 2023-04-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_profile_dark_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('image', models.ImageField(default='/home/user/Документы/Django/SocialNetwork/static/img/avatar/default.jpg', upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Zavod',
        ),
    ]
