# Generated by Django 4.1.7 on 2023-05-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
