# Generated by Django 4.1.7 on 2023-05-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to='network.profile'),
        ),
    ]
