# Generated by Django 4.1.7 on 2023-04-17 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messanger', '0003_alter_message_chat_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='user_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
